### PR TITLE
Adding more kaomoji, formatted json

### PR DESCRIPTION
**Pull request by spronkets**
Added table double flip, soviet russia table flips you, moved table unflip next to table flip, updated keywords
Source (plenty more where that came from): http://tableflipping.com/

Formatted json because it wasn't consistent

### CODE REVIEW

**Review by naseem-qadium — APPROVED** [review]

**Comment by naseem-qadium** [comment]
Someone buy this man a drink.

**Review by jlmart88 — APPROVED** [review]
Thanks for the PR! I'll be sure to get this redeployed soon

**Comment by lawqdm** [comment]
＼(＾▽＾)／

**Comment by spronkets** [comment]
No problem thanks for the fun :)

**Comment by jlmart88** [comment]
@kcrossman deployed!

**Pull request merged**
